Feat/depub
likecoin/likecoin-discord-bot pull request #1
Opened 2022-08-05 03:14 UTC by lancatlin

+ Allow user to depub a message by message context menu
+ Respond iscn widget link to let user finish the transaction

Other changes:
+ Refactor the structure of commands
+ Combine register-commands into main workflow

2022-08-05 07:12 UTC, WeiJun0827 approved these changes

2022-08-08 15:27 UTC, williamchong requested changes

2022-08-08 15:27 UTC, williamchong commented on src/register-commands.js
> +    console.log(command.data.name);
Please print more context if this `console.log` is suppose to be kept

2022-08-08 15:27 UTC, williamchong commented on src/register-commands.js
> +  const commands = await Promise.all(commandFiles.map(async (file) => {
By dynamically importing these js from `commands`, does that mean we will lose lint checking/future typescript support?

2022-08-08 15:27 UTC, williamchong commented on src/register-commands.js
> +    .catch(console.error);
Please stick to `await` if we are using `async` in function

2022-08-08 15:27 UTC, williamchong commented on src/commands/depub.js
> +    const msgContent = msg.content.substring(0, 200);
Please add `...` in the end if we actually substring?
maybe use Unicode Character “…” (U+2026) if thats save some space

2022-08-08 15:27 UTC, williamchong commented on src/commands/depub.js
> +import { ApplicationCommandType } from 'discord-api-types/v10';
Are we mixing `v10` here and `v9` api type below?

2022-08-09 04:09 UTC, lancatlin commented on src/commands/depub.js
> +    const msgContent = msg.content.substring(0, 200);
I think unicode whold be encoded to %E2%80%A6 since it's not IRI.

2022-08-09 04:25 UTC, lancatlin commented on src/register-commands.js
> +  const commands = await Promise.all(commandFiles.map(async (file) => {
Yes it affects. I removed the dynamic importing.

2022-08-09 04:25 UTC, lancatlin commented on src/commands/depub.js
> +import { ApplicationCommandType } from 'discord-api-types/v10';
Updated all to v10

2022-08-09 08:17 UTC, williamchong requested changes

2022-08-09 08:17 UTC, williamchong commented on src/commands/depub.js
> +      description: `${msgUrl}\n${msg.author.username}: ${msgContent}...\n#Discord #${guildName}`,
Can we add `...` only when the content actually hit the string length limit?

2022-08-09 08:40 UTC, lancatlin commented on src/commands/depub.js
> +      description: `${msgUrl}\n${msg.author.username}: ${msgContent}...\n#Discord #${guildName}`,
Updated

2022-08-09 09:23 UTC, WeiJun0827 approved these changes

2022-08-09 09:37 UTC, nwingt commented on src/commands/depub.js
> +    const msgContent = msg.content.substring(0, 200);
200 can be a const or config?

2022-08-09 09:37 UTC, nwingt commented on src/commands/translate.js
> +    if (interaction.channel.id !== TARGET_CHANNEL_ID) {
TARGET_CHANNEL_ID seems too generic for `/translate`
how about sth like  `CHANNEL_ID_FOR_TRANSLATE`

2022-08-10 06:46 UTC, merged