Feat/send like
likecoin/likecoin-discord-bot pull request #6
Opened 2022-08-22 03:51 UTC by lancatlin

+ `/register` to set receiving address
+ `/deposit` to set sending address and sign authz
+ `/balance` to check deposited balance
+ `/send` to send LIKE to other who registered receiving address

2022-08-23 03:04 UTC, lancatlin commented
I will change it to mainnet once the review is completed.

2022-08-29 09:30 UTC, nnkken reviewed
Please change all `console.error(err)` to `console.error(err.stack || err)`

2022-08-29 09:30 UTC, nnkken commented on backend/src/db.js
> +export async function initDB() {
Any consequence if we call `initDB` multiple times?
(e.g. multiple files calling `initDB` during initialization)

2022-08-29 09:30 UTC, nnkken commented on backend/src/db.js
> +    console.error(err);
Should not catch here. At least not a general `catch` for the whole function.
In general, if a function called `initDB` failed, it means you should not use the DB.
In this case, rather than logging an error and letting the caller continue execution (without noticing that the DB 
instance is in an unknown state), letting the error throwing outside is a better way:
if the caller is not aware of it, it won't continue execution;
if the caller thinks it can handle it, the caller may explicitly handle it.

2022-08-29 09:30 UTC, nnkken commented on backend/src/router.js
> +      .catch(() => {}); // Ignore error if DM is disabled
Why `console.warn` in one case while empty handler in another case?

2022-08-29 09:30 UTC, nnkken commented on backend/src/utils/deposit.js
> +  const hash = await bcrypt.hash(String(discordId), saltRounds);
Why using `bcrypt` here? What is the security concern / model?

2022-08-29 09:52 UTC, WeiJun0827 commented on packages/config/index.js
> +export const WALLET_CONFIG = isDev
Usually, use `IS_TESTNET` to distinguish if the `NODE_ENV` is `'production'`.

```suggestion
export const IS_TESTNET = NODE_ENV !== 'production'
export const ENDPOINT = IS_TESTNET
  ? 'https://node.testnet.like.co'
  : 'https://mainnet-node.like.co'

export const WIDGET_ENDPOINT = IS_TESTNET
  ? 'https://testnet.like.co'
  : 'https://like.co'

export const WALLET_CONFIG = IS_TESTNET
```

2022-08-29 09:52 UTC, WeiJun0827 commented on backend/src/config.js
> +  DB_PASS,
```suggestion
  DB_PASSWORD,
```

2022-08-29 10:24 UTC, williamchong commented
> console.error(err.stack || err)

do `err.stack` guaranteed to have content of `err.toString()`?

2022-08-29 11:18 UTC, nnkken commented
> > console.error(err.stack || err)
> 
> do `err.stack` guaranteed to have content of `err.toString()`?

Seems at least for NodeJS, yes
https://nodejs.org/docs/latest-v16.x/api/errors.html#errorstack

2022-08-29 11:33 UTC, williamchong requested changes
I just finished backend part, will continue on frontend

2022-08-29 11:33 UTC, williamchong commented on backend/src/commands/send.js
> +        content: `${user} want to send LIKE to ${receiverUser} but they doesn't have receiving address, need to \`/register\` first.`,
```suggestion
        content: `${user} want to send LIKE to ${receiverUser} but they doesn't have receiving address, please \`/register\` first to receive LIKE.`,
```

2022-08-29 11:33 UTC, williamchong commented on backend/src/index.js
> +client.login(TOKEN);
So the bot and api are running in a same service?

2022-08-29 11:33 UTC, williamchong commented on backend/src/router.js
> +      .catch(console.warn); // Ignore error if DM is disabled
Should we require user to use DM for `/deposit` and `/register` in order to enable DM?

2022-08-29 11:33 UTC, williamchong commented on backend/src/router.js
> +  const session = await Session.findOne({ where: { token } });
Please add expiry for sessions

2022-08-29 11:33 UTC, williamchong commented on backend/src/router.js
> +    if (!session) { throw new Error('SESSION_NOT_FOUND'); }
Please add expiry for sessions

2022-08-29 11:33 UTC, williamchong commented on backend/src/router.js
> +  console.error(err.stack);
Should we log both stack and err.toString()?

2022-08-29 11:33 UTC, williamchong commented on backend/src/utils/deposit.js
> +  const hash = await bcrypt.hash(String(discordId), saltRounds);
After we have API do we need those memo now? Would deposit fail to be used if we change salt? How can we rotate if something is leaked?

2022-08-29 11:33 UTC, williamchong commented on backend/src/utils/deposit.js
> +  if (!session) { throw new Error('SESSION_NOT_FOUND'); }
Please check session expiry

2022-08-29 11:33 UTC, williamchong commented on backend/src/utils/utils.js
> +  const amount = Number(nanoAmount) / (10 ** WALLET_CONFIG.coinDecimals);
Prefer bignumber.js

2022-08-29 11:33 UTC, williamchong commented on backend/src/utils/utils.js
> +  if (addr.startsWith('like1')) { return addr.length === 43; }
Use bech32 for checking is more robust

2022-08-29 11:33 UTC, williamchong commented on backend/src/utils/verify.js
> +    return await queryBalance(user);
Can we just check the deposit wallet from db, and check the grant from that wallet instead of memo now? no point in verifying deposit if grant would get overwritten

2022-08-29 11:33 UTC, williamchong commented on backend/src/utils/wallet.js
> +      amount: String(amount),
if it's nanolike, I think it should be passed as string from the begining since bignumber

2022-08-29 11:47 UTC, williamchong requested changes

2022-08-29 11:47 UTC, williamchong commented on frontend/assets/css/index.css
> +  font-family: Arial, Helvetica, sans-serif;
I think we prefer `Open Sans`

2022-08-29 11:47 UTC, williamchong commented on frontend/components/Wallet.vue
> +      logout: 'wallet/logout',
Normally we would wrap this mutation in an action so that we don't need to handle mutation in component

2022-08-29 11:47 UTC, williamchong commented on frontend/nuxt.config.js
> +    '@nuxtjs/proxy',
What does this proxy do? Can we just hit backend api without proxy?

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/deposit.vue
> +      <p>The money will keep in your wallet until you /send it</p>
```suggestion
      <p>The amount of LIKE granted will still stay in your wallet until you send it</p>
```

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/deposit.vue
> +    demon: WALLET_CONFIG.coinDenom,
```suggestion
    denom: WALLET_CONFIG.coinDenom,
```

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/deposit.vue
> +      <label>Authorized amount: <input v-model="amount" type="number">{{ demon }}</label>
```suggestion
      <label>Authorized amount: <input v-model="amount" type="number">{{ denom }}</label>
```

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/deposit.vue
> +        <p>Tx: <a :href="`${ENDPOINT}/cosmos/tx/v1beta1/txs/${txHash}`">{{ txHash }}</a></p>
Please go to bigdipper

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/deposit.vue
> +      await this.$store.dispatch('wallet/createSendGrant', { amount: this.amount, memo: this.hash })
Why this is not wrapped in try catch?

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/register.vue
> +        this.isSending = false
Should set in a finally block?

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/register.vue
> +      } catch (err) {
Please console.error(err) too

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/deposit.vue
> +      } catch (err) {
Please console.error(err) too

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/register.vue
> +        Sending...
```suggestion
        Registering...
```

2022-08-29 11:47 UTC, williamchong commented on frontend/pages/register.vue
> +      <p v-if="isDone">
v-else-if? also isDone should override isSending

2022-08-29 11:47 UTC, williamchong commented on frontend/store/wallet.js
> +      ? `${state.connector.restURL}/cosmos/tx/v1beta1/txs/${state.txHash}`
If for UI display, please use bigdipper

2022-08-29 11:47 UTC, williamchong commented on frontend/store/wallet.js
> +    connector.disconnect()
should this be in action instead?

2022-08-29 13:16 UTC, nwingt commented on frontend/pages/deposit.vue
> +        <p>Authorized success! Now use /balance to check your deposit and /send to send the LIKE to others!</p>
```suggestion
        <p>Authorized success! Now use <code>/balance</code> to check your deposit and <code>/send</code> to send the LIKE to others!</p>
```

2022-08-29 13:16 UTC, nwingt commented on frontend/pages/deposit.vue
> +      Link invalid. Please use /deposit to generate a new one
```suggestion
      Link invalid. Please use <code>/deposit</code> to generate a new one
```

2022-08-29 13:16 UTC, nwingt commented on frontend/pages/deposit.vue
> +        <p>Tx: <a :href="`${ENDPOINT}/cosmos/tx/v1beta1/txs/${txHash}`">{{ txHash }}</a></p>
Can use computed property without passing the constant to data

2022-08-29 13:16 UTC, nwingt commented on frontend/pages/register.vue
> +    <div v-else-if="valid">
Can use template for just wrapper without extra div
```suggestion
    <template v-else-if="valid">
```

2022-08-29 13:16 UTC, nwingt commented on frontend/store/wallet.js
> +    connector.disconnect()
Yes, this is an async function

2022-08-29 13:16 UTC, nwingt commented on frontend/store/wallet.js
> +        LikeCoinWalletConnectorMethodType.KeplrMobile,
Keplr Mobile does not support sendGrant, can remove this method from selection

2022-08-30 03:42 UTC, lancatlin commented on backend/src/utils/deposit.js
> +  const hash = await bcrypt.hash(String(discordId), saltRounds);
We don't need to store salt. It verify the memo on chain with user's discord id. It's only used for protecting privacy for user. Because all the verification is on chain, our db security can be less important (which only stores receive & send address) and more concrete while user may do some operation on their own (like revoking grant, grant for other discord id).

2022-08-30 03:45 UTC, lancatlin commented on .github/workflows/cd.yml
> +          UI_BASE: https://lancatlin.github.io
I removed GitHub Action since it has API.

2022-08-30 03:47 UTC, lancatlin commented on backend/src/client.js
> +  await registerCommands();
I found another API that I can set up commands for all guilds & DM.

2022-08-30 03:53 UTC, lancatlin commented on backend/src/db.js
> +  username: {
Not used in code so far.

2022-08-30 03:56 UTC, lancatlin commented on backend/src/delete-commands.js
> +  rest.put(Routes.applicationCommands(CLIENT_ID), { body: [] })
https://discord.com/developers/docs/interactions/application-commands#registering-a-command
I register commands for all guilds & DM

2022-08-30 03:57 UTC, lancatlin commented on backend/src/index.js
> +client.login(TOKEN);
Yes. As we need API to send discord message sometimes.

2022-08-30 05:15 UTC, lancatlin commented on backend/src/utils/utils.js
> +  const amount = Number(nanoAmount) / (10 ** WALLET_CONFIG.coinDecimals);
How about the built-in BigInt?

2022-08-30 05:19 UTC, lancatlin commented on backend/src/utils/verify.js
> +    return await queryBalance(user);
One wallet may be granted to other discord user (to chain it is still the same), so checking every time is more concrete.

2022-08-30 05:22 UTC, lancatlin commented on frontend/nuxt.config.js
> +    '@nuxtjs/proxy',
It's only for development purposes. I don't know your plan of deployment. I serve the static frontend and reverse proxy `/api` to backend.

2022-08-30 05:50 UTC, lancatlin commented on backend/src/config.js
> +  DB_PASS,
I think DB_PASS is also used in indexer

2022-08-31 03:18 UTC, lancatlin commented on backend/src/router.js
> +      .catch(console.warn); // Ignore error if DM is disabled
Fixed

2022-08-31 10:28 UTC, williamchong requested changes
Some final adjustment, thank for the hard work

2022-08-31 10:28 UTC, williamchong commented on backend/src/commands/send.js
> +    console.log(nanoAmount);
Please remove console.log

2022-08-31 10:28 UTC, williamchong commented on backend/src/utils/utils.js
> +        content: 'Please open DM to continue',
`Please direct message me to use this command`

2022-08-31 11:36 UTC, lancatlin commented on backend/src/utils/utils.js
> +        content: 'Please open DM to continue',
In this case, it will still send the message to dm. This is just notify user to check the dm (although they should get notify already).

2022-08-31 11:38 UTC, lancatlin commented on backend/src/utils/utils.js
> +        content: 'Please open DM to continue',
Because I think it would be better that user use this command in everywhere, and be leaded to DM without send the command again.

2022-08-31 15:29 UTC, williamchong commented on backend/src/utils/utils.js
> +        content: 'Please open DM to continue',
but if user did not dm bot first, bot cannot dm them right? So is it preferable that we always guide user to message us?
Also in any case, we should use the word "message" instead of DM to avoid confusion

2022-09-01 02:22 UTC, lancatlin commented on backend/src/utils/utils.js
> +        content: 'Please open DM to continue',
Yes, bot can dm them first as long as they enable the privacy settings. User cannot dm the bot without changing the privacy setting.

2022-09-01 21:27 UTC, williamchong approved these changes
Thanks for contributing all these

2022-09-01 21:27 UTC, merged